version: "3"

services: 
  nginx:
    ports:
      - "80:80"
  node-app:
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    env_file:
      - ./.env
    command: node index.js
    