version: "3"

services: 
  nginx:
    ports:
      - "3000:80"
  node-app:
    volumes:
      - .:/usr/src/app
      - /node_modules
    environment:
      - NODE_ENV:development
      - PORT:3000
      - MONGO_USER=bhanu
      - MONGO_PASSWORD=12345678
    env_file:
      - ./.env
    command: npm run dev
      
  mongo:
    environment: 
      - MONGO_INITDB_ROOT_USERNAME=bhanu
      - MONGO_INITDB_ROOT_PASSWORD=12345678